export const usersInfo = [
  {
    id: 1,
    name: "Valentina Rossi",
    email: "valentina.rossi@bending-spoons.com",
    phone: "+39 02 4548 9203",
    address: "Corso Buenos Aires 33, 20124 Milano MI, Italia",
    role: "Senior Frontend Engineer",
    department: "Platform",
    status: "active",
    joinDate: "2022-03-15",
    country: "Italy",
    countryCode: "IT",
    timezone: "Europe/Rome",
    locale: "it-IT",
    lastLogin: "2025-02-15T09:42:00Z",
    avatarColor: "#E07A5F",
  },
  {
    id: 2,
    name: "Kenji Tanaka",
    email: "tanaka.kenji@mercari.com",
    phone: "+81 3-6632-8841",
    address: "Roppongi Hills Mori Tower 36F, 6-10-1 Roppongi, Minato-ku, Tokyo 106-6136",
    role: "Lead UX Designer",
    department: "Design Systems",
    status: "active",
    joinDate: "2021-08-03",
    country: "Japan",
    countryCode: "JP",
    timezone: "Asia/Tokyo",
    locale: "ja-JP",
    lastLogin: "2025-02-16T02:18:00Z",
    avatarColor: "#3D405B",
  },
  {
    id: 3,
    name: "Amara Okonkwo",
    email: "a.okonkwo@flutterwave.com",
    phone: "+234 803 715 9823",
    address: "1684 Sanusi Fafunwa St, Victoria Island, Lagos 101001",
    role: "Staff Product Manager",
    department: "Payments",
    status: "on leave",
    joinDate: "2023-01-10",
    country: "Nigeria",
    countryCode: "NG",
    timezone: "Africa/Lagos",
    locale: "en-NG",
    lastLogin: "2025-02-08T14:30:00Z",
    avatarColor: "#81B29A",
  },
  {
    id: 4,
    name: "Santiago Morales",
    email: "smorales@cornershop.com",
    phone: "+56 9 4521 8834",
    address: "Av. Apoquindo 4800, Torre Titanium, Piso 16, Las Condes, Santiago",
    role: "Backend Engineer",
    department: "Logistics",
    status: "active",
    joinDate: "2022-11-22",
    country: "Chile",
    countryCode: "CL",
    timezone: "America/Santiago",
    locale: "es-CL",
    lastLogin: "2025-02-16T15:05:00Z",
    avatarColor: "#F2CC8F",
  },
  {
    id: 5,
    name: "Freya Lindqvist",
    email: "freya.lindqvist@spotify.com",
    phone: "+46 8 588 117 00",
    address: "Regeringsgatan 19, 111 53 Stockholm",
    role: "Principal Data Engineer",
    department: "Analytics",
    status: "active",
    joinDate: "2020-06-08",
    country: "Sweden",
    countryCode: "SE",
    timezone: "Europe/Stockholm",
    locale: "sv-SE",
    lastLogin: "2025-02-16T11:22:00Z",
    avatarColor: "#1DB954",
  },
];

export const purchaseHistory = [
  { id: 1, userId: 1, productName: "Logitech MX Master 3S", quantity: 1, unitPrice: 99.99, currency: "EUR", date: "2025-01-12" },
  { id: 2, userId: 1, productName: "Keychron K8 Pro", quantity: 1, unitPrice: 109.00, currency: "EUR", date: "2025-02-03" },
  { id: 3, userId: 2, productName: "Wacom Intuos Pro M", quantity: 1, unitPrice: 349.00, currency: "JPY", date: "2024-11-28" },
  { id: 4, userId: 2, productName: "Figma Professional", quantity: 1, unitPrice: 12.00, currency: "USD", date: "2025-02-01" },
  { id: 5, userId: 3, productName: "Notion Team", quantity: 1, unitPrice: 8.00, currency: "USD", date: "2024-12-15" },
  { id: 6, userId: 3, productName: "Miro Business", quantity: 1, unitPrice: 8.00, currency: "USD", date: "2025-01-20" },
  { id: 7, userId: 4, productName: "AWS Credits Pack 500", quantity: 2, unitPrice: 250.00, currency: "USD", date: "2025-02-10" },
  { id: 8, userId: 4, productName: "Datadog Pro", quantity: 1, unitPrice: 15.00, currency: "USD", date: "2025-02-14" },
  { id: 9, userId: 5, productName: "Snowflake Compute", quantity: 1, unitPrice: 40.00, currency: "USD", date: "2025-01-05" },
  { id: 10, userId: 5, productName: "dbt Cloud Team", quantity: 1, unitPrice: 100.00, currency: "USD", date: "2025-02-08" },
];

export const userConfiguration = [
  {
    id: 1,
    userId: 1,
    configuration: {
      theme: "light",
      language: "it",
      notifications: { email: true, push: true, digest: "weekly" },
      currency: "EUR",
      compactMode: false,
    },
  },
  {
    id: 2,
    userId: 2,
    configuration: {
      theme: "dark",
      language: "ja",
      notifications: { email: true, push: false, digest: "daily" },
      currency: "JPY",
      compactMode: true,
    },
  },
  {
    id: 3,
    userId: 3,
    configuration: {
      theme: "system",
      language: "en",
      notifications: { email: true, push: true, digest: "never" },
      currency: "NGN",
      compactMode: false,
    },
  },
  {
    id: 4,
    userId: 4,
    configuration: {
      theme: "dark",
      language: "es",
      notifications: { email: true, push: true, digest: "weekly" },
      currency: "CLP",
      compactMode: true,
    },
  },
  {
    id: 5,
    userId: 5,
    configuration: {
      theme: "light",
      language: "sv",
      notifications: { email: false, push: true, digest: "daily" },
      currency: "SEK",
      compactMode: false,
    },
  },
];
